name: Purge APIM

on:
  workflow_dispatch:
    inputs:
      api-management:
        description: "API Management instance to purge"
        required: true
        type: string
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prd

permissions:
  contents: read
  id-token: write

jobs:
  purge:
    runs-on: ubuntu-latest
    name: Purge APIM in ${{ github.event.inputs.environment }}
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: azure/login@v2.1.0
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/cli@v2.0.0
        name: Purge APIM
        with:
          azcliversion: latest
          inlineScript: |
            az rest --method delete --url https://management.azure.com/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.ApiManagement/locations/${{ vars.LOCATION }}/deletedservices/${{ github.event.inputs.api-management }}?api-version=2022-08-01
