name: Deploy Frontend Reusable

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "Environment to deploy to"
        type: string
        default: "dev"
      artifact-name:
        required: true
        description: "Artifact name to download"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Download App Artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ github.workspace }}/${{ inputs.artifact-name }}

      - name: Update Placeholders
        env:
          WORKING_DIR: ${{ github.workspace }}/${{ inputs.artifact-name }}/assets
        run: |
          sed -i "s/__API_KEY__/${{ secrets.BACKEND_API_SUBSCRIPTION_KEY }}/g" $WORKING_DIR/*.js

      - uses: azure/login@v2.1.0
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/webapps-deploy
        name: Deploy to Azure Web App
        with:
          resource-group: ${{ vars.RG_NAME }}
          webapp-name: ${{ vars.FRONTEND_APP_SERVICE_NAME }}
          package: ${{ github.workspace }}/${{ inputs.artifact-name }}
