name: Deploy GitHub Runner Reusable

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "Environment to deploy to"
        type: string
        default: "dev"

permissions:
  id-token: write
  contents: read

env:
  CONTAINER_IMAGE_NAME: "github-actions-runner"
  WORKING_DIR: "${{ github.workspace }}/infra/github-runner/"

jobs:
  deploy_runner:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Build and Deploy Runner to ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: azure/login@v2.1.0
        name: Login to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/acr-build-deploy
        name: Build and Deploy to ACR
        id: acr-build-deploy
        with:
          container-registry-name: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}
          resource-group: ${{ vars.RG_NAME }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          image-name: ${{ env.CONTAINER_IMAGE_NAME }}
          image-tag: ${{ github.sha }}
          working-dir: ${{ env.WORKING_DIR }}

      - name: Deploy Runner
        id: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RG_NAME }}
          template: ./infra/github-runner.bicep
          failOnStdErr: false
          deploymentName: "deploy-gh-runner-${{ github.run_id }}"
          region: ${{ vars.LOCATION }}
          parameters: >
            repoOwner=${{ github.repository_owner }}
            repoName=${{ github.event.repository.name }}  
            containerRegistryName=${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}
            imageName=${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
            runnerName=github-runner-${{ inputs.environment }}            
            runnerSubnetId=${{ vars.GH_RUNNER_SUBNET_ID }}
            runnerIdentityName=${{ vars.GH_RUNNER_IDENTITY_NAME }}  
            runnerLabels="['${{ inputs.environment }}']"
            runnerDnsServerPrimary=${{ vars.GH_RUNNER_DNS_SERVER_PRIMARY }}
            runnerDnsServerSecondary=${{ vars.GH_RUNNER_DNS_SERVER_SECONDARY }}
            githubToken=${{ secrets.MANAGE_GH_RUNNERS_PAT }}
